- hosts: app
  vars:
    tomcat_ver: 9.0.52                          # Tomcat version to install
    ui_manager_user: manager                    # User who can access the UI manager section only
    ui_manager_pass: 123456                     # UI manager user password
    ui_admin_username: admin                    # User who can access bpth manager and admin UI sections
    ui_admin_pass: 123456                       # UI admin password

  roles:
    - role: internal/tomcat

- hosts: lb
  vars:
    haproxy_package_name:           haproxy
    haproxy_frontend_port:          80
    haproxy_backend_port:           8080
  roles:
    - role: internal/haproxy

